### ISSUE TITLE
404: page not found

### ISSUE THREAD

**Issue by ykai16** [nucleome/nucleserver#3]
Hi,

I tried to start a nucleosome browser using the demo google sheet (I downloaded it as .xlsx). The program seems to run successfully (see following message), but when I went to the default local host: http:/127.0.0.1:8611, it has a "404 page not found" error. Did I do it correctly? or any tips to get away this error? Thanks!

(base) Yans-MacBook-Pro:Downloads ykai$ ./nucleserver start -i NucleoServerDemo1.xlsx
2020/06/30 19:44:57 Loading genome hg19
2020/06/30 19:44:57   Loading sheet ENCODE
2020/06/30 19:45:01     Loading entry ChIPSeqMTA1
2020/06/30 19:45:03   Loading sheet ENCODE_ChIPSeq
2020/06/30 19:45:08     Loading entry MTA1
2020/06/30 19:45:17 Successful loaded 2 sheets
Using Ctrl-C to Quit Program
2020/06/30 19:45:17 Data service is on port 8611

**Comment by nimezhu** [comment]
It is not a error, open Nucleome Browser http://vis.nucleome.org , instead of http://127.0.0.1:8611, you will see your data there
